version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3 # docker hubからイメージを取得する
    executor: ruby/default
    steps:
      - checkout
      - run: #runのnameごとにステップが分かれて実行される
          name: gem install # ステップ名
          command: gem install bundler:2.0.2 # 実行されるコマンド
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }} # キャッシュ(Gemfile.lock)をリストアに保存する
            - v1-dependencies-
      - run:
          name: Which bundler?
          command: bundle -v
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }} # インストール済みのライブラリをキャッシュする

  build_image:
    docker:
      - image: docker:19.03.8
    steps:
      - checkout
      - setup_remote_docker
      # AWS CLIのインストール
      - run:
          name: install aws cli # 実行コマンドの名前
          command: |
            apk add --no-cache --update py-pip
            pip install awscli
      # AWS CLIを使用してECRにログイン
      - run:
          name: login ecr
          command: |
            $(aws ecr get-login --no-include-email --region ap-northeast-1)
      # Dockerイメージのビルド
      - run:
          name: build image
          # ${circleciで設定した環境変数}で参照できる。
          command: |
            docker build -t ${ECR_DOMAIN}:$CIRCLE_SHA1 -t ${ECR_DOMAIN}:latest .
      # ビルドしたイメージをECRにpush
      - run:
          name: Push docker image
          command: |
            docker push ${ECR_DOMAIN}:$CIRCLE_SHA1
            docker push ${ECR_DOMAIN}:latest

workflows:
  version: 2
  test:
    jobs:
      - build # jobs.buildを実行
      - build_image: # jobs.build_imageを実行
          # jobs.buildを実行後
          requires:
            - build
          filters:
            branches:
              only: master
