version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3 # docker hubからイメージを取得する
    executor: ruby/default
    steps:
      - checkout
      - run: #runのnameごとにステップが分かれて実行される
          name: gem install # ステップ名
          command: gem install bundler:2.0.2 # 実行されるコマンド
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }} # キャッシュ(Gemfile.lock)をリストアに保存する
            - v1-dependencies-
      - run:
          name: Which bundler?
          command: bundle -v
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }} # インストール済みのライブラリをキャッシュする

workflows:
  version: 2.1
  test:
    jobs:
      - build
      - build_image:
        requires:
          - build
          filters:
            branches:
              only: master